name: Java CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build and test with Maven
      run: mvn clean test
    - name: Upload Surefire Reports
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports
        path: target/surefire-reports
